#!/usr/bin/env bash
# Function to get record type and destination

get_record() {
    local domain=$1
    local subdomain=$2
    local record
    record=$(dig "$subdomain"."$domain" | awk '/^;; ANSWER SECTION:$/ { getline ; print $4, $5 }')
    echo "The subdomain $subdomain is a ${record%% * } record and points to ${record##* }"
}

if [ -z "$1" ]; then
    echo "Please provide a domain."
    exit 1
fi

if [ -n "$2" ]; then
    get_record "$1" "$2"
else
    for subdomain in www lb-01 web-01 web-02; do
        get_record "$1" "$subdomain"
    done
fi
