#!/bin/bash
# Update the package lists for upgrades and new package installations
sudo apt-get update -y
sudo apt-get install nginx -y
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        return 200 'Hello World!';
        add_header Content-Type text/plain;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
