#!/bin/bash

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Define custom HTTP header configuration
header_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location / {
        try_files $uri $uri/ =404;
        add_header X-Served-By \$hostname;
    }
}"

# Write custom configuration to Nginx default site configuration file
echo "$header_config" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
sudo systemctl restart nginx

