#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
