#!/usr/bin/env bash
#9. Process and PID file

echo $$ > /var/run/myscript.pid

handle_sigterm() {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 0
}

handle_sigint() {
	echo "Y U love me?!"
}

handle_sigquit() {
	rm /var/run/myscript.pid
	exit 0
}

trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
