#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 {start|stop|restart}"
	exit 1
fi

PID_FILE="/var/run/my_process.pid"

start_process() {
	if [ -f "$PID_FILE" ]; then
		echo "manage_my_process is already running."
		exit 1
	fi
	./manage_my_process &
	PID=$!
	echo $PID > "$PID_FILE"
	echo "manage_my_process started"
}

stop_process() {
	if [ ! -f "$PID_FILE" ]; then
		echo "manage_my_process is not running."
		exit 1
	fi
	PID=$(cat "$PID_FILE")
	kill $PID
	rm "$PID_FILE"
	echo "manage_my_process stopped"
}

restart_process() {
	stop_process
	start_process
	echo "manage_my_process restarted"
}

case "$1" in
	start)
		start_process
		;;
	stop)
		stop_process
		;;
	restart)
		restart_process
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
