#!/usr/bin/env bash
#Define a function to run when a SIGTERM signal is received

handle_sigterm() {
	echo "I am invincible!!!"
	exit 0
}

trap 'handle_sigterm' SIGTERM

while true
do
        echo "To infinity and beyond"
        sleep 2
done
