#!/usr/bin/env bash
# 12. Tell the story of passwd

exec 3< /etc/passwd
while IFS=: read -r username uid gid gecos homedir shell <&3; do

	IFS=',' read -r fullname _ _ info <<< "$gecos"
	IFS=' ' read -r _ groupname - <<< "$(grep ":$gid:" /etc/group)"
	
	echo "The user $username is part of the $gid gang, lives in $homedir, and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"

done

echo 3<&-
